services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: taskdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: clave-secreta-docker
      DEBUG: "True"
    depends_on:
      - db

volumes:
  postgres_data: